### ISSUE TITLE
'tabulate' dependency not supported

### ISSUE THREAD

**Issue by Pyrofoux** [caranha/AIWolfCompo#3]
The python codebase has a dependency for the _tabulate_ library, in `utility.py`, line 5.
```
from tabulate import tabulate
```
However, this library isn't supported in the official game server environment, as you can see in this agent log : 

```
Traceback (most recent call last):
  File "/home/aiwolf/contest/test/data/54/FoxuFoxu/omgyousuck.py", line 19, in <module>
    from utility import *
  File "/home/aiwolf/contest/test/data/54/FoxuFoxu/utility.py", line 5, in <module>
    from tabulate import tabulate
ModuleNotFoundError: No module named 'tabulate'
```

tabulate would be very useful to read game logs, and would prove very valuable for new developers like me who want to get started with the Python codebase.

Would it be possible to either support _tabulate_ in the official environment, or to make it so the python codebase doesn't rely on it ?

**Comment by Pyrofoux** [comment]
(Sorry, I just realised this is in the wrong repo)

**Comment by caranha** [comment]
Hey Pyro, 

You are right, this is not the right repo, but I will send your message to the server admin.

Cheers!
